name: Deno Install Test
on: [push]

jobs:
  install:
    name: "Deno Install"
    runs-on: ubuntu-18.04
    container:
      image: centos:8
    steps:
      - run: dnf install -y unzip
      # - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      # - run: echo "::add-path::/github/home/.deno/bin"
      # - run: echo $PATH
      # - run: whereis deno
      # - run: deno run https://deno.land/std/examples/welcome.ts
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno --version
